### ISSUE TITLE
Add a diagram to /sources describing how the metadata is manipulated

### ISSUE THREAD

**Issue by flaneuse** [NIAID-Data-Ecosystem/nde-portal#111] opened 2022-10-27 22:32 UTC
Won't want to create this till more of the post-processing is worked out, but will eventually want to have a methodology diagram showing what happens on the data pipeline to get and improve the metadata. For example: harvest metadata from source, standardize variable names to schema, transform types, standardize formats, normalize/standardize values (connect to ontologies), entity recognition/extraction, resource linkage, etc.  Basically, documentation (in the form of a pretty diagram) of how we transform and standardize the metadata we import.

Shouldn't be tackled at the moment (since we're still working it out!) but wanted to add an issue to remember to track it.

**Comment by candicecz** [comment] 2023-10-17 12:36
Duplicate of methodology page

**Closed by candicecz** 2023-10-17 12:36 UTC
Labels: long-term, low priority
