### ISSUE TITLE
Download Metadata button seems not working

### ISSUE THREAD

**Issue by newgene** [NIAID-Data-Ecosystem/nde-portal#211] opened 2023-11-08 23:59 UTC
The buttons in both result page and dataset detail page are not working right now.

**Comment by candicecz** [comment] 2023-11-09 01:06
@newgene  Something seems strange with the `_scroll_id` parameter returned by the API. Can you double check if you are encountering the same issue?

This is the API call that is first fired and returns the `_scroll_id`: https://api.data.niaid.nih.gov/v1/query?&q=%22Asthma%22&extra_filter=&facet_size=1000&size=10&from=0&sort=_score&dotfield=true&fetch_all=true&page=0

This is the second call: 
https://api.data.niaid.nih.gov/v1/query?&q=%22Asthma%22&extra_filter=&facet_size=1000&size=10&from=0&sort=_score&dotfield=true&fetch_all=true&page=0&scroll_id=[SCROLL_ID]

The second call fails when I try it.

**Comment by newgene** [comment] 2023-11-09 05:25
@candicecz After the first call, which you get the `scroll_id` back, then the following call you can pass only `scroll_id=[SCROLL_ID]`. Not sure if it's related to the error you see, but that should be the right way of using `scroll_id`.

**Comment by newgene** [comment] 2023-11-09 17:10
adding @jal347 to this issue, so he can take a look.

**Comment by DylanWelzel** [comment] 2023-11-09 18:34
The issue was caused by overriding the the `build` function to add the option of hiding the `_meta` property and not handling the possibility of a scroll ID, moving the functionality to the `apply_extras` was the solution. Also during this process we updated the biothings api to 0.12.3. This was applied to all 3 api's (prod,staging,dev)

[Moved hide _meta commit](https://github.com/NIAID-Data-Ecosystem/nde-discovery-api/commit/84888272daff348dd0954dd1995402471a417585)

[biothings api update commit](https://github.com/NIAID-Data-Ecosystem/nde-discovery-api/commit/95634a242895443504f4fdb1975587d510f827c4)

If everything works correctly @candicecz you can close this

**Comment by newgene** [comment] 2023-11-09 20:04
👍 @DylanWelzel this reminds us we should a set of tests to cover API calls used by the UI (can be another issue).

**Comment by DylanWelzel** [comment] 2023-11-09 20:06
Yeah I completely agree

**Closed** 2023-11-09 21:35 UTC
Labels: bug
